<?php
/**
 * Route Settings
 *
 * Created by PhpStorm.
 * User: DevMode
 * Date: 7/20/14
 * Time: 9:14 PM
 */

$route_settings = array(
    'Area' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Associate' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'AssociateContact' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Branch' => array(
        'post_method' => true,
        'update' => true,
        'patch' => true,
        'get_all' => true,
        'get_by_id' => true,
        'count' => true,
    ),
    'BranchVariable' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Contact' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Customer' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'CustomerVariable' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Department' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Discount' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'GlobalSetting' => array(
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
    ),
    'HappyHour' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'HappyHourTiming' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'InventoryGroup' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'InventoryItem' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Item' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'ItemHappyHour' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'ItemIngredient' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'ItemModifier' => array(
        'create' => true,
        'update_priority' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'ItemTag' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'ItemTimeSitting' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Location' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'LocationVariable' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'MenuCategory' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'MenuCategoryItem' => array(
        'create' => true,
        'update_priority' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'MenuCategoryModifier' => array(
        'create' => true,
        'update_priority' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'MenuGroup' => array(
        'create' => true,
        'update_priority' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'MenuGroupCategory' => array(
        'create' => true,
        'update_priority' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Modifier' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'ModifierOption' => array(
        'create' => true,
        'update_priority' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Module' => array(
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
    ),
    'OperatingTime' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'PaymentMode' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Printer' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Role' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'RoleAccess' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Shift' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'SpecialOperationDate' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'SpecialTurnTime' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Tag' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'Tax' => array(
        'create' => true,
        'update_priority' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'TaxProfile' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'TimeSitting' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'TransactionType' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'User' => array(
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'UserCredential' => array(
        'custom_get' => array(
            'getToken' => '/permissions(:parameters)',
        ),
        'create' => true,
        'update_status' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
    'UserRole' => array(
        'create' => true,
        'post_method' => true,
        'get_all' => true,
        'count' => true,
        'get_by_id' => true,
        'update' => true,
        'patch' => true,
        'delete' => true,
    ),
);